### ISSUE TITLE
Add comments to patch yml file

### ISSUE THREAD

**Issue by danngreen** [4ms/metamodule#15]
Name of module, name of jack or knob after each ID:
```yml
  mapped_ins:
    - panel_jack_id: 6. # F
      ins:
        - module_id: 1 # Seq8
          jack_id: 0 #CV Out
  mapped_knobs:
    - panel_knob_id: 0 # A
      module_id: 2 # MultiLFO
      param_id: 0 # Freq
      curve_type: 0
      min: 0
      max: 1


```
